config/routes.rb
Rails.application.routes.draw do
  # 顧客側
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    root to: 'homes#top'
    resources :notifications, only: [:index, :destroy]
    resources :recruitments, only: [:new, :create, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :customers, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      member do
        get :favorites
      end
    end
  end
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show]
    resources :styles, only: [:index, :create, :edit, :update, :destroy]
    resources :play_times, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :recruitments, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < ApplicationController
  def index
    @style = Style.new
    @styles = Style.all
  end

  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:notice] = "作成しました。"
      redirect_to admin_styles_path
    else
      @styles = Style.all
      render :index
    end
  end

  def edit
    @style = Style.find(params[:id])
  end

  def update
    @style = Style.find(params[:id])
    if @style.update(style_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_styles_path
    else
      @styles = Style.all
      render :index
    end
  end

  def destroy
    @style = Style.find(params[:id])
    @style.destroy
    flash[:notice] = "削除しました。"
    redirect_to admin_styles_path
  end

  private

  def style_params
    params.require(:style).permit(:name)
  end
end

app/helpers/admin/styles_helper.rb
module Admin::StylesHelper
end

app/views/admin/styles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-3 text-center">
      <h2>プレイスタイル編集画面</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-12 p-3 text-center">
      <%= form_with model: @style, url: admin_style_path, method: :patch do |f| %>
        <label for="inputName">プレイスタイル</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"プレイスタイル" %>
        <%= f.submit '保存', class:"btn btn-info btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/styles/index.html.erb
<div class="container">
	<%= render "admin/shared/flash" %>
	<div class="row">
		<div class="col-12 p-2 text-center">
			<h2>プレイスタイル追加・一覧</h2>
		</div>
	</div>

	<div class="row">
		<div class="col-12 p-3 text-center">
			<% if @style.errors.any? %>
				<%= @style.errors.count %>件のエラーが発生しました
					<% @style.errors.full_messages.each do |message| %>
						 <li><%= message %></li>
				<% end %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-12 p-3 text-center">
			<%= form_with model: @style, url: admin_styles_path, method: :post do |f| %>
				<%= f.text_field :name, placeholder: "プレイスタイル" %>
				<%= f.submit "追加", class:"btn btn-primary btn-sm" %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-6 p-2 mx-auto">
			<table class="table">
				<thead>
					<tr>
						<th>プレイスタイル</th>
					  <th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @styles.each do |style| %>
						<tr>
							<td><%= style.name %></td>
							<td><%= link_to "編集する", edit_admin_style_path(style.id), class:"btn btn-success btn-sm" %></td>
							<td><%= link_to "削除", admin_style_path(style.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger btn-sm" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>