config/routes.rb
Rails.application.routes.draw do
  # 顧客側
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    root to: 'homes#top'
    resources :notifications, only: [:index, :destroy]
    resources :recruitments, only: [:new, :create, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :customers, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      member do
        get :favorites
      end
    end
  end
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show]
    resources :styles, only: [:index, :create, :edit, :update, :destroy]
    resources :play_times, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recruitments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-2 text-center">
      <h2>顧客一覧</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-8 p-2 mx-auto">
      <table class="table">
        <thead>
          <tr>
            <th>No.</th>
            <th>氏名</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td><%= customer.name %></td>
              <td><%= link_to "詳細", admin_customer_path(customer.id), class: "btn btn-secondary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-2 text-center">
      <h2><%= @customer.name %>さんの詳細</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-7 p-2 mx-auto">
      <table class="table">
        <tr><th class="col-5">いいね数</th><td class="col-2"><%= @customer.favorites.count %></td></tr>
        <tr><th class="col-5">コメント数</th><td class="col-2"><%= @customer.comments.count %></td></tr>
        <tr><th class="col-5">作成日</th><td class="col-2"><%= @customer.created_at.strftime('%Y/%m/%d') %></td></tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-12 p-3 text-center">
      <%= link_to "戻る", admin_customers_path, class: "btn btn-info" %>
    </div>
  </div>
</div>