config/routes.rb
Rails.application.routes.draw do
  # 顧客側
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    root to: 'homes#top'
    resources :notifications, only: [:index, :destroy]
    resources :recruitments, only: [:new, :create, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :customers, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      member do
        get :favorites
      end
    end
  end
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show]
    resources :styles, only: [:index, :create, :edit, :update, :destroy]
    resources :play_times, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/play_time.rb
class PlayTime < ApplicationRecord
  has_many :recruitments, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/play_times_controller.rb
class Admin::PlayTimesController < ApplicationController
  def index
    @play_time = PlayTime.new
    @play_times = PlayTime.all
  end

  def create
    @play_time = PlayTime.new(play_time_params)
    if @play_time.save
      flash[:notice] = "作成しました。"
      redirect_to admin_play_times_path
    else
      @play_times = PlayTime.all
      render :index
    end
  end

  def edit
    @play_time = PlayTime.find(params[:id])
  end

  def update
    @play_time = PlayTime.find(params[:id])
    if @play_time.update(play_time_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_play_times_path
    else
      @play_times = PlayTime.all
      render :index
    end
  end

  def destroy
    @play_time = PlayTime.find(params[:id])
    @play_time.destroy
    flash[:notice] = "削除しました。"
    redirect_to admin_play_times_path
  end

  private

  def play_time_params
    params.require(:play_time).permit(:name)
  end
end

app/helpers/admin/play_times_helper.rb
module Admin::PlayTimesHelper
end

app/views/admin/play_times/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-3 text-center">
      <h2>募集時間編集画面</h2>
    </div>
  </div>
  <div class="col-12 text-center">
    <%= form_with model: @play_time, url: admin_play_time_path, method: :patch do |f| %>
      <label for="inputName">プレイ時間</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"プレイ時間" %>
      <%= f.submit '保存', class:"btn btn-info btn-sm" %>
    <% end %>
  </div>
</div>

app/views/admin/play_times/index.html.erb
<div class="container">
	<%= render "admin/shared/flash" %>
	<div class="row">
		<div class="col-12 p-2 text-center">
			<h2>募集時間一覧・追加</h2>
		</div>
	</div>
	<div class="row">
		<div class="col-12 p-3 text-center">
			<% if @play_time.errors.any? %>
			  <%= @play_time.errors.count %>件のエラーが発生しました
			    <% @play_time.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-12 p-3 text-center">
			<%= form_with model: @play_time, url: admin_play_times_path, method: :post do |f| %>
				<%= f.text_field :name, placeholder: "募集時間" %>
				<%= f.submit "追加", class:"btn btn-primary btn-sm" %>
			<% end %>
		</div>
	</div>

	<div class="row">
		<div class="col-6 p-2 mx-auto">
			<table class="table">
				<thead>
					<tr>
						<th>募集時間</th>
					  <th colspan="3"></th>
					</tr>
				</thead>
				<tbody>
					<% @play_times.each do |play_time| %>
						<tr>
							<td><%= play_time.name %></td>
							<td><%= link_to "編集する", edit_admin_play_time_path(play_time.id), class:"btn btn-success btn-sm" %></td>
							<td><%= link_to "削除", admin_play_time_path(play_time.id), method: :delete, data: {confirm: "削除しますか？"}, class:"btn btn-danger btn-sm" %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>