config/routes.rb
Rails.application.routes.draw do
  # 顧客側
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  namespace :public do
    root to: 'homes#top'
    resources :notifications, only: [:index, :destroy]
    resources :recruitments, only: [:new, :create, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :customers, only: [:show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
      member do
        get :favorites
      end
    end
  end
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show]
    resources :styles, only: [:index, :create, :edit, :update, :destroy]
    resources :play_times, only: [:index, :create, :edit, :update, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recruitment
  has_many :notifications, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recruitments, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visiter_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :recruitment
  has_many :notifications, dependent: :destroy
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :recruitment, optional: true
  belongs_to :comment, optional: true
  belongs_to :visiter, class_name: 'Customer', foreign_key: 'visiter_id', optional: true
  belongs_to :visited, class_name: 'Customer', foreign_key: 'visited_id', optional: true
end

app/models/play_time.rb
class PlayTime < ApplicationRecord
  has_many :recruitments, dependent: :destroy

  validates :name, presence: true
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  belongs_to :style
  belongs_to :play_time
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :recruitment_letter, presence: true

  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end

  def create_notification_favorite!(current_customer)
    temp = Notification.where(["visiter_id = ? and visited_id = ? and recruitment_id = ? and action = ? ", current_customer.id, customer_id, id, 'favorite'])
    if temp.blank?
      notification = current_customer.active_notifications.new(
        recruitment_id: id,
        visited_id: customer_id,
        action: 'favorite'
      )
      if notification.visiter_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_customer, comment_id)
    temp_ids = Comment.select(:customer_id).where(recruitment_id: id).where.not(customer_id: current_customer.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_customer, comment_id, temp_id['customer_id'])
    end
    save_notification_comment!(current_customer, comment_id, customer_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_customer, comment_id, visited_id)
    notification = current_customer.active_notifications.new(
      recruitment_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )

    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :recruitments, dependent: :destroy
  
  validates :name, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/styles_controller.rb
class Admin::StylesController < ApplicationController
  def index
    @style = Style.new
    @styles = Style.all
  end

  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:notice] = "作成しました。"
      redirect_to admin_styles_path
    else
      @styles = Style.all
      render :index
    end
  end

  def edit
    @style = Style.find(params[:id])
  end

  def update
    @style = Style.find(params[:id])
    if @style.update(style_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_styles_path
    else
      @styles = Style.all
      render :index
    end
  end

  def destroy
    @style = Style.find(params[:id])
    @style.destroy
    flash[:notice] = "削除しました。"
    redirect_to admin_styles_path
  end

  private

  def style_params
    params.require(:style).permit(:name)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/play_times_helper.rb
module Admin::PlayTimesHelper
end

app/helpers/admin/styles_helper.rb
module Admin::StylesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_flash.html.erb
<div class="row">
    <div class="col-12 p-3 text-center">
        <% if flash[:notice] %>
            <p>
                <%= flash[:notice] %>
            </p>
        <% end %>
    </div>
</div>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
　　<div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom bg-dark text-white pt-5 pb-5">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-md-12 text-center">
        <p>ゲーム仲間を見つけるコミュニティーサイト</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top shadow">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark text-white p-3">
      <div class="container">
        <strong>
          <% if customer_signed_in? %>
            <%= link_to "GAME COMMUNITY", public_root_path, class: "btn btn-outline-info" %>
          <% else admin_signed_in? %>
            <%= link_to "GAME COMMUNITY", admin_root_path, class: "btn btn-outline-info" %>
          <% end %>
        </strong>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to public_notifications_path do %>
                  <i class="fas fa-exclamation fa-lg"></i>通知
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to new_public_recruitment_path do %>
                  <i class="fas fa-plus-square fa-lg"></i>募集投稿
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to favorites_public_customer_path(current_customer.id) do %>
                  <i class="fas fa-thumbs-up fa-lg"></i>いいね一覧
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to public_customer_path(current_customer.id) do %>
                  <i class="fas fa-users fa-lg"></i>マイページ
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to destroy_customer_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt fa-lg"></i>ログアウト
                <% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to admin_styles_path do %>
                  <i class="fas fa-walking fa-lg"></i>プレイスタイル
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to admin_play_times_path do %>
                  <i class="fas fa-clock fa-lg"></i>募集時間
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to admin_customers_path do %>
                  <i class="fas fa-users fa-lg"></i>ユーザー一覧
                <% end %>
              </li>
              <li class="nav-item mr-4 btn btn-outline-warning">
                <%= link_to destroy_admin_session_path, method: :delete do %>
                  <i class="fas fa-sign-out-alt fa-lg"></i>ログアウト
                <% end %>
              </li>
            <% else %>
              <li class="nav-item mr-5 btn btn-outline-warning">
                <%= link_to  new_customer_registration_path do %>
                  <i class="fas fa-user-plus fa-lg"></i>新規登録
                <% end %>
              </li>
              <li class="nav-item mr-5 btn btn-outline-warning">
                <%= link_to new_customer_session_path do %>
                   <i class="fas fa-sign-in-alt fa-lg"></i>ログイン
                <% end %>
              </li>
              <li class="nav-item mr-5 btn btn-outline-warning">
                <%= link_to customers_guest_sign_in_path, method: :post do %>
                  <i class="fas fa-key fa-lg"></i>ゲストログイン
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameRecruitmentSpace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <main class="mb-auto">
      <%= yield %>
    </main>
    
    <%= render "layouts/footer" %>
  </body>
</html>